[package]
name = "n-star-api"
version = "1.0.0"
edition = "2021"

[dependencies]
actix-cors = "0.6.5"
actix-web = "4.4.1"
reqwest = { version = "0.11.23", features = ["json"] }
serde_json = "1.0.108"
tokio = { version = "1.35.1", features = ["full"] }
